steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-east1-docker.pkg.dev/microservices-422001/image-registry/products-ms",
        "-f",
        "Dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/microservices-422001/image-registry/products-ms",
      ]

availableSecrets:
  secretManager:
  - versionName: projects/367390259998/secrets/orders_ms_database_url/versions/1
    env: 'DATABASE_URL'